

[redis]
uri="redis://127.0.0.1/"

[http]
port = 3000

###

[[http.mappings]]
path = "/home/smrt/w/yew-axum-template/frontend/dist"
target = "/dist"

###

[[http.mappings]]
path = "/home/smrt/w/yew-axum-template/server/assets/css"
target = "/css"

[[http.mappings]]
path = "/home/smrt/w/yew-axum-template/server/assets/www"
target = "/www"
