
root = "/home/smrt/w/yew-axum-template/"


[redis]
uri="redis://127.0.0.1/"

[http]
port = 3000

###

[[http.mappings]]
path = "frontend/dist"
target = "/dist"
fallback = "index.html"

[[http.mappings]]
path = "server/assets/css"
target = "/css"

#[[http.mappings]]
#path = "server/assets/www"
#target = "/www"
