root = "/home/smrt/w/yew-axum-template/"
invitation_code = "oslo"


[redis]
uri="redis://127.0.0.1/"

[http]
port = 3000
app_home = "/dist/home"

[storage]
path = "db"

###

[[http.mappings]]
path = "frontend/dist"
target = "/dist"
fallback = "index.html"

[[http.mappings]]
path = "server/assets/css"
target = "/css"
fallback = "app.css"
