[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
macros = { path = "../macros" }
axum = { version = "0.8.6", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.16"


[features]
server = [ "axum" ]
default = []
frontend = []

